### ISSUE TITLE
failing installation on centos 6.7

### ISSUE THREAD

**Issue by mpodber1971** [kislyuk/keymaker#15]
i perform same steps on centos 7 which installs without issue.  when i try to install on centos 6.7, i get the following error message:

/etc/ssh/sshd_config: line 141: Bad configuration option: AuthorizedKeysCommandUser
    amazon-ebs: /etc/ssh/sshd_config: line 143: Bad configuration option: AuthenticationMethods
    amazon-ebs: /etc/ssh/sshd_config: terminating, 2 bad configuration options
    amazon-ebs: Traceback (most recent call last):
    amazon-ebs: File "/usr/bin/keymaker", line 87, in <module>
    amazon-ebs: locals()[args.command](args)
    amazon-ebs: File "/usr/lib/python2.6/site-packages/keymaker/__init__.py", line 118, in install
    amazon-ebs: subprocess.check_call(["sshd", "-t"])
    amazon-ebs: File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    amazon-ebs: raise CalledProcessError(retcode, cmd)
    amazon-ebs: subprocess.CalledProcessError: Command '[u'sshd', u'-t']' returned non-zero exit status 255

**Comment by kislyuk** [comment]
`AuthorizedKeysCommandUser` was introduced in OpenSSH v6.2. Keymaker is not usable without it. What's the default version on centos 6.7? Is it upgradeable?
