### ISSUE TITLE
updated comprehensive documentation

### ISSUE THREAD

**Issue by CentraOP** [kislyuk/keymaker#32]
I still seem to have issues with the configure command on the latest version. If this command is not vital could we get more precise documentation on set up and use. I would be happy to help write the docs if i could get some more explanations.

**Comment by kislyuk** [comment]
The docs are a work in progress. I'm happy to take PRs. Can you be specific as to the problems you encountered?

**Comment by CentraOP** [comment]
sudo keymaker list_keys
Traceback (most recent call last):
  File "/usr/local/bin/keymaker", line 89, in <module>
    locals()[args.command](args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keymaker/__init__.py", line 209, in list_keys
    user = iam.CurrentUser().user
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/resources/factory.py", line 431, in get_reference
    self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 615, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the GetUser operation: Must specify userName when calling with non-User credentials

This after the latest version which still doesnt seem to support configure. thanks!

**Comment by kislyuk** [comment]
Have you tried following the directions in the error message?

**Comment by CentraOP** [comment]
I add the iam name at the end of the command and it says 
keymaker: error: unrecognized arguments: 

Is there some command line switch to be included or a particular order. None of that is clear from the readme which is why im asking for more documentation and I am happy to contribute back or make a post about it. thanks!

**Comment by kislyuk** [comment]
You are welcome to contribute PRs that make documentation clearer for you. There is a minimum level of experience with AWS and command-line utilities required to use this package. In your case you need to read and understand the "principle of operation" section of the Keymaker documentation and understand how to manage your IAM credentials. You also need to understand how to use the `--help` option to read online documentation for command-line utilities.
